### ISSUE TITLE
os.file.ZIP_PATH resolve error; builds failing under Windows

### ISSUE THREAD

**Issue by justin-bits** [ngageoint/opensphere-build-resolver#50]
Failed at the xxx compile:resolve script
Error: Unable to resolve module path for define os.file.ZIP_PATH with path zip-js/WebContent

**Comment by wallw-bits** [comment]
That has already been addressed in the latest version. Please upgrade your libraries/applications to use version `^6.0.0` of `opensphere-build-resolver`.
